[greeter]
background=/usr/share/backgrounds/daemoncore/core-horizon.png
theme-name=DaemonCore-Dark
icon-theme-name=Adwaita
font-name=Sans 11
indicators=~host;~spacer;~clock;~spacer;~session;~language;~a11y;~power
