LIVE_HOSTNAME="daemoncore"
LIVE_USERNAME="daemon"
LIVE_USER_FULLNAME="DaemonCore Live User"
LIVE_USER_DEFAULT_GROUPS="audio cdrom dip floppy video plugdev netdev powerdev scanner bluetooth wireshark"

